index:
    path: /{_locale}
    defaults: { _controller: 'App\Controller\TechNews\IndexController::index', _locale: 'fr' }
    requirements:
        _locale: en|fr

# Utilisation du RedirectController
# https://symfony.com/doc/current/routing/redirect_in_config.html#redirecting-using-a-route
accueil:
    path: /{_locale}/accueil
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: index
        permanent: true

# Exemple d'utilisation du TemplateController
# On imagine ici avoir créer un fichier mentionslegales.html.twig
# https://symfony.com/doc/current/templating/render_without_controller.html
mentions_legales:
    path:         /mentions-legales
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: static/mentionslegales.html.twig

deconnexion:
    path: /deconnexion